### ISSUE TITLE
Spec clarifications

### ISSUE THREAD

**Issue by joelanders** [TheTorProject/ooni-spec#101]
```
If ALL of the connections succeed then we consider the endpoint to not be blocked.

Conversely if all attempts fail then we consider the endpoint to be blocked and mark is as such in the report:
```
Probably the first "ALL" should be "any."

Also the Whatsapp and Telegram tests say they only TCP connect to "consistent" IPs, but we now want to TCP to all of them (but only consider the "consistent" ones in saying "blocked" or "unblocked").

**Comment by hellais** [comment]
I made these changes to the whatsapp test spec. @joelanders can you maybe look at the other specs and make the required changes to those too?

**Comment by joelanders** [comment]
Maybe also another point clarifying that "whatsapp_endpoints_blocked" only means "we tried to connect to a consistent IP and failed" and not just more generically "blocked".
